# Interactive component

## Our Process
When working with the data, one of the questions that arose in our minds was whether or not the perception students' had on the diversity of their own schools was grounded in reality. Upon investigating this question, we noticed that generally, as demographic representation rose across schools, so did the students' satisfaction with their school's diversity. We noticed a limitation of our visualization where the individual identity of the schools was lost. This graph also made it difficult to actually compare the relative proportions of each school, since we weren't able to track schools across the different facets. 

We figured that a great way to see how the proportions change as student diversity sentiment increases would be to create an animation of sorts, a lot like [this](https://observablehq.com/@mbostock/bar-chart-race-with-scrubber), where we could easily get a general sense of changing proportions across the dataset. Unfortunately, after much time trying to get the modules of Observable working locally, as well as some failed attempts on the Observable platform itself, we decided to code something on our own in D3 that would hopefully be as similar to the Observable notebook as possible.


## Our Solution

[Hosted on VizHub](https://vizhub.com/bhernandev/ddf32c3cb542443681d9b0a9152c5f66?edit=files)

In the end we implemented something that we believe is just as good if not better than the original linked Observable notebook. Implemented with D3 and some JQuery,  we were able to implement a slider that allows us to scroll through schools from the lowest diversity sentiment to the highest. This updates a bar graph below the slider, that shows the actual diversity breakdown of the given school.

We actually think that this solution is better than the bar chart race since the static positions of the bars gives us a stronger ability to actually track how the demographics are changing and is also much less distracting. We were also able to have a vertical bar chart instead of the horizontal one from the notebook, which also facilitates quick comparisons of the demographic breakdowns.
