# Conclusion

## Limitations

There are several limitations that we have identified during the research.

From the data collection perspective. The collection of census data has not included educational related variables except the college degree statistics. As researchers, we have to manually join the datasets tables and conduct laborious processes of data cleansing. If the data collection techniques could be improved to cover educational details based on school located in tracts (from when the raw data are collected), it will make our research more convenient. However, as we understand the scale of NYC census datasets has its own limitations, we still try to diminish the limitation brought from the original raw data to its minimum influence.

With respect to our diversity data and methods, a stronger study might’ve perhaps included an increased granularity on the sentiment of the students on diversity. As of right now it was purely a binary sentiment and having levels would allow for stronger associations to be made. Similarly increased granularity in the demographic breakdowns of the schools would make for a much stronger study, as there was only 5 different categories without even accommodating for overlap.

Among the datasets that were both published by the DOE were even inconsistencies, such as in the number of students recorded, as discussed in the data cleaning process. The drawback of such census data or government issued survey data is that unlike private entities that have the ability to acquire their user data, governmental surveys cannot enforce respondents’ answers. Demographical data in that sense are more complete than other reported statistics such as graduation rates or college rates, students’ satisfaction, etc. To deal with such inconsistencies, we selected the values based on its completeness and recalculated other values based on that population data.




## Lessons learned

The research and data investigation process of this project provided insightful conclusions. 

From the datasets, we have seen the strong and constant funding support from NYC government to elementary public schools and middle schools. The widely distributed public school system is what ensures the education equity of the New York people. From the rivalry between charter schools and the public schools in high school institution level, we suggest that the public high school in New York might need more support from the government side.

The intermediate schools, aiming for students in Grade 7-8, have become a popular option for NYC parents after the graduation of their kids from a 6-year education after Grade 6, surprisingly to us. The number of intermediate schools are almost the same as both of its counterpart and substitutional options combined: K-8, K-12 schools.

From the datasets, we also investigated the vocational schools and the special education schools, these 2 categories of education institution are important for families in low income status. In our research, there are less than 30 vocational schools in total and around 20 special education schools in NYC. There could be more schools for the people in these 2 groups. By revealing and visualizing these data on the map, we also would like to use this project to advocate for people with their disabilities and from families without financial support for education.

With respect to the discrepancies between the experienced diversity and the actual diversity across various NYC high schools, we seem to have discovered little to no evidence for a huge difference. From our precursory exploration of the data, scatterplots, and dynamic visualizations, we were able to get a sense that the lived experience of students was perfectly in line with the diversity of their schools. However, as a result of some of the aforementioned limitations in our data and methods, more work would need to be done before making any definitive conclusions!


